blockchain:
  nodes:
    self:
      host: localhost
      port: 8080
      publish-rate-ms: 60000
    topic:
      name: node-topic

spring:
  kafka:
    bootstrap-servers: localhost:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer