name: Java CD
on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Install GitVersion
        uses: gittools/actions/gitversion/setup@v0.9.7
        with:
          versionSpec: '5.x'
      - name: Determine Version
        uses: gittools/actions/gitversion/execute@v0.9.7
      - name: Display SemVer
        run: |
          echo "SemVer: $GITVERSION_MAJORMINORPATCH"

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
      - name: Build with Maven
        run: mvn package -Dmaven.test.skip

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push the blockchain-miner Docker image
        run: |
          docker build . --tag ghcr.io/danuser2018/blockchain-miner:$GITVERSION_MAJORMINORPATCH
          docker tag ghcr.io/danuser2018/blockchain-miner:$GITVERSION_MAJORMINORPATCH ghcr.io/danuser2018/blockchain-miner:latest
          docker push ghcr.io/danuser2018/blockchain-miner:$GITVERSION_MAJORMINORPATCH
          docker push ghcr.io/danuser2018/blockchain-miner:latest  
